<?php
/**
 * Created by PhpStorm.
 * User: 10765
 * Date: 2019/4/11
 * Time: 22:08
 */
namespace controller\admin;
use controller\Controller;

class AdminController extends Controller {
    protected $admin = null;

    function __init()
    {
        return parent::__init(); // TODO: Change the autogenerated stub
    }
}