<?php
/**
 * Created by PhpStorm.
 * User: 10765
 * Date: 2019/4/13
 * Time: 18:27
 */
namespace controller\admin;
class AdminAuth extends AdminController {
    public function __init()
    {
        parent::__init(); // TODO: Change the autogenerated stub
        if($uid = $_SESSION['admin_uid']) {
            $user = \modal\admin\User::getUserByUid($uid);
            if($user) {
                $this->admin = $user;
                _S('admin', $user);
            }
        }
        if(empty($this->admin)) {
            return redirect('/index.php/admin/login/index');
        }
        return true;
    }
}